#!/bin/sh

PATH=/bin:/usr/bin:/sbin:/usr/sbin:/usr/local/bin
export PATH

exec 2>&1
exec setuidgid deploy bash -c '
  cd /srv/irc-bot/current;
  source /etc/profile;
  bundle exec ruby bots/bami2.rb
'

